version: "3"

services:
  bp-api:
    build: ./server
    container_name: bp-api
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
